<a href="https://colab.research.google.com/github/SANDESHAHAHA/Data_Science/blob/main/BasicNumpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import random
x=random.randint(100)
print(x)

0


In [ ]:
from numpy import random
x=random.rand()
print(x)

[0.44421401 0.34054436 0.64671265]


In [ ]:
from numpy import random
x=random.randint(100,size=(5))
print(x)

[37 67  1 29 19]


In [ ]:
from numpy import random
x=random.randint(100,size=(3,6))
print(x)

[[49  8 72  2 86 54]
 [94 86 98  6 86 24]
 [48 19 42 63 34 40]]


In [ ]:
from numpy import random
x=random.rand(3,5)
print(x)

[[0.98996    0.7033211  0.60547748 0.11351083 0.03788998]
 [0.50399187 0.53065494 0.74713999 0.68120096 0.72020224]
 [0.44007219 0.09888644 0.68360834 0.78439722 0.19971659]]


In [ ]:
from numpy import random
x=random.choice([3,4,5,6,7,9])
print(x)

4


In [ ]:
from numpy import random
x=random.choice([2,4,5,6,7,4,3],size=(3,4))
print(x)

[[4 5 5 6]
 [2 3 6 7]
 [2 3 2 5]]


Random Data Distribution


In [ ]:
from numpy import random
x=random.choice([1,2,3,4,5],p=[0.1,0.2,0.3,0.0,0.4],size=(5,5))
print(x)

[[3 2 3 2 3]
 [3 5 5 3 5]
 [2 3 1 3 3]
 [5 3 2 5 2]
 [3 5 3 5 2]]


In [ ]:
import numpy as np
from numpy import random
arr=np.array([1,2,3,6,4,5])
random.shuffle(arr)
print(arr)

[4 1 5 3 2 6]


In [ ]:
import numpy as np
from numpy  import random
arr=np.array([1,2,3,5,4])
newarr=random.permutation(arr)
print(newarr)

[1 5 3 2 4]


Note : Shuffle changes to the original array and permutation makes a copy and returns a new array.
