<a href="https://colab.research.google.com/github/SANDESHAHAHA/Data_Science/blob/main/Gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow import keras

In [2]:
df=pd.read_csv("/content/insurance_data.csv")

In [3]:
df.head()

,age,affordibility,bought_insurance
0,22,1,0
1,25,0,0
2,47,1,1
3,52,0,0
4,46,1,1


In [4]:
df.shape

(28, 3)

In [5]:
df.isnull().sum()

,0
age,0
affordibility,0
bought_insurance,0


In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test=train_test_split(df[['affordibility','age']],df.bought_insurance,test_size=0.2,random_state=25)

In [8]:
len(X_train)

22

In [9]:
len(X_test)

6

In [10]:
X_train

,affordibility,age
0,1,22
13,0,29
6,0,55
17,1,58
24,1,50
19,1,18
25,1,54
16,0,25
20,1,21
3,0,52


In [11]:
X_train_scaled=X_train.copy()
X_train_scaled['age']=X_train_scaled['age']/100

X_test_scaled=X_test.copy()
X_test_scaled['age']=X_test_scaled['age']/100

In [12]:
X_train_scaled

,affordibility,age
0,1,0.22
13,0,0.29
6,0,0.55
17,1,0.58
24,1,0.50
19,1,0.18
25,1,0.54
16,0,0.25
20,1,0.21
3,0,0.52


In [13]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
    #they are just weight and bias if you dont initialize the parameters it wont be problem at all the built in function in tf will automatically decide those parameters.

])
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(X_train_scaled,y_train,epochs=5000)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Streaming output truncated to the last 5000 lines.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.7273 - loss: 0.5321
Epoch 2502/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.7273 - loss: 0.5321
Epoch 2503/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.7273 - loss: 0.5321
Epoch 2504/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.7273 - loss: 0.5320
Epoch 2505/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.7273 - loss: 0.5320
Epoch 2506/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.7273 - loss: 0.5320
Epoch 2507/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.7273 - loss: 0.5319
Epoch 2508/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.7273 - loss: 0.5319
Epoch 2509/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7273 - loss: 0.5318
Epoch 2510/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7273 - loss: 0.5318
Epoch 2511/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7273 - loss: 0.5

In [14]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 505ms/step - accuracy: 1.0000 - loss: 0.3550


[0.35497763752937317, 1.0]

In [15]:
X_test_scaled

,affordibility,age
2,1,0.47
10,1,0.18
21,0,0.26
11,1,0.28
14,1,0.49
9,1,0.61


In [16]:
y_test

,bought_insurance
2,1
10,0
21,0
11,0
14,1
9,1


In [17]:
predictions=model.predict(X_test_scaled)
predictions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 270ms/step


array([[0.7054848 ],
       [0.3556957 ],
       [0.16827835],
       [0.4780119 ],
       [0.7260696 ],
       [0.8294983 ]], dtype=float32)

In [18]:
y_actual_predictions=(predictions>=0.5).astype(int)
y_actual_predictions

array([[1],
       [0],
       [0],
       [0],
       [1],
       [1]])

In [19]:
#knowing the weights
coef,intercept=model.get_weights()
coef,intercept

(array([[1.408652 ],
        [5.0608625]], dtype=float32),
 array([-2.9137027], dtype=float32))

implementing in python

In [20]:
def sigmoid(x):
 import math
 return 1/(1+math.exp(-x))
sigmoid(16)

0.9999998874648379

In [21]:
def prediction_function(age,affordability):
  weighted_sum=coef[0]*age+coef[1]*affordability+intercept
  return sigmoid(weighted_sum)

In [22]:
prediction_function(.47,1)

<ipython-input-20-41872bf8f8af>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))


0.9431723630699127

In [23]:
def logloss(y_true,y_actual_predictions):
  epsilon=1e-15
  y_predicted_new=np.clip(y_actual_predictions,epsilon,1-epsilon)
  return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [26]:
#it gives the sigmoid of the entire array
def sigmoid_numpy(X):
  return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [44]:
def gradient_descent(age,affordability,y_true,epochs,loss_thresold=0.4631):
  w1=w2=1
  bias=0
  rate=0.1
  n=len(age)
  for i in range(epochs):
    weighted_sum= w1*age+w2*affordability+bias
    y_predicted=sigmoid_numpy(weighted_sum)
    loss=logloss(y_true,y_predicted)
    w1d=(1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
    w2d=(1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))
    bias=np.mean(y_predicted-y_true)
    w1=w1-rate*w1d
    w2=w2-rate*w2d
    print(f'epoch:{i},w1:{w1},w2:{w2},bias:{bias},loss:{loss}')
    if loss<=loss_thresold:
      break
  return w1,w2,bias

In [45]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,1000)

epoch:0,w1:0.9949815266940354,w2:0.9896696250789058,bias:0.22683735472737165,loss:0.7113403233723417
epoch:1,w1:0.9884526125464794,w2:0.9773435933265646,bias:0.2660212531686501,loss:0.7658470543639112
epoch:2,w1:0.9817316862045118,w2:0.9648095514835985,bias:0.2711467907421431,loss:0.7744067241510453
epoch:3,w1:0.9750411205661081,w2:0.9523626196540338,bias:0.2704992735780208,loss:0.7737785814297374
epoch:4,w1:0.9684183566228521,w2:0.9400525963188087,bias:0.26888019088784143,loss:0.7716178237443305
epoch:5,w1:0.96186973675356,w2:0.9278880413546495,bias:0.26709724126214146,loss:0.7692413368046052
epoch:6,w1:0.9553963311235584,w2:0.9158704828139532,bias:0.2652872323228762,loss:0.7668695016053279
epoch:7,w1:0.9489982936695974,w2:0.9040002059198157,bias:0.2634738767272211,loss:0.7645389701669295
epoch:8,w1:0.9426756014958794,w2:0.8922772398164557,bias:0.26166170337970035,loss:0.7622555892512513
epoch:9,w1:0.9364281812775919,w2:0.8807015270377698,bias:0.25985196366113567,loss:0.76001999844721

(np.float64(0.4137448490021443),
 np.float64(0.2949001990432335),
 np.float64(0.11447271766124571))

In [43]:
coef,intercept

(array([[1.408652 ],
        [5.0608625]], dtype=float32),
 array([-2.9137027], dtype=float32))